# frozen_string_literal: true

babies = [
  { name: 'Merritt', birthday: '2014-02-10', mother_name: 'Winifred Pollard', father_name: 'Ferdinand Gibbs', address: '4480 Egestas. Av.' },
  { name: 'Cherokee', birthday: '2014-08-12', mother_name: 'Dahlia Castro', father_name: 'Zeus Huff', address: '311-7263 Cras St.' },
  { name: 'Justin', birthday: '2014-12-15', mother_name: 'Miriam Vincent', father_name: 'Edan Jacobs', address: '5466 Luctus Street' },
  { name: 'Felicia', birthday: '2015-09-17', mother_name: 'Anjolie Herring', father_name: 'Ali Walker', address: '436-5429 Fermentum Street' },
  { name: 'Kylynn', birthday: '2016-04-14', mother_name: 'Heidi Frank', father_name: 'Lee Pacheco', address: 'P.O. Box 675, 1364 Quam. St.' },
  { name: 'Sigourney', birthday: '2014-02-04', mother_name: 'Piper Mckee', father_name: 'Martin Blackburn', address: '8165 Facilisis Rd.' },
  { name: 'Cadman', birthday: '2015-04-04', mother_name: 'Rama Roach', father_name: 'Joseph Hester', address: 'P.O. Box 347, 1647 Id Rd.' },
  { name: 'Odessa', birthday: '2014-07-22', mother_name: 'Adena Willis', father_name: 'Cody Neal', address: 'P.O. Box 175, 6045 Magnis Av.' },
  { name: 'May', birthday: '2015-10-04', mother_name: 'Irene Mason', father_name: 'Hayden Wynn', address: 'P.O. Box 894, 1672 Vulputate Avenue' },
  { name: 'Germaine', birthday: '2016-06-22', mother_name: 'Lacota Drake', father_name: 'Dexter Guerrero', address: '2766 Odio, Ave' },
  { name: 'Cameron', birthday: '2014-01-20', mother_name: 'Leslie Campos', father_name: 'Lucas Carney', address: '7906 Sed St.' },
  { name: 'Ivan', birthday: '2016-04-27', mother_name: 'Guinevere Mosley', father_name: 'Simon Henderson', address: '287-2764 Massa. Road' },
  { name: 'Orlando', birthday: '2014-04-07', mother_name: 'Odessa Foley', father_name: 'Bernard Warner', address: 'P.O. Box 110, 8239 Congue Av.' },
  { name: 'Florence', birthday: '2014-11-08', mother_name: 'Diana Vargas', father_name: 'Gannon Wolfe', address: '6175 Dictum. Rd.' },
  { name: 'Gannon', birthday: '2015-02-14', mother_name: 'Vera Booker', father_name: 'Armando Obrien', address: 'P.O. Box 864, 5585 Purus Street' },
  { name: 'Quincy', birthday: '2016-01-15', mother_name: 'Heidi Anthony', father_name: 'Evan Figueroa', address: 'Ap #528-435 Taciti Av.' },
  { name: 'Carter', birthday: '2014-01-15', mother_name: 'Chloe Barlow', father_name: 'Simon Miller', address: 'Ap #370-2298 Amet St.' },
  { name: 'Aspen', birthday: '2015-06-30', mother_name: 'Althea Avila', father_name: 'Malik Perez', address: '9727 Ligula. St.' },
  { name: 'Nicole', birthday: '2015-05-03', mother_name: 'Cameron Stevens', father_name: 'Alan James', address: '2452 Placerat Rd.' },
  { name: 'Zephr', birthday: '2016-03-31', mother_name: 'Maxine Riggs', father_name: 'Lev Nieves', address: '466-3407 Taciti Avenue' },
  { name: 'Charde', birthday: '2015-05-31', mother_name: 'Raven Velasquez', father_name: 'Fletcher Quinn', address: '650-590 Vivamus Road' },
  { name: 'Hall', birthday: '2014-07-22', mother_name: 'Leigh Navarro', father_name: 'Fulton Newman', address: 'P.O. Box 791, 6991 Pretium Rd.' },
  { name: 'Yvette', birthday: '2015-03-03', mother_name: 'Erin Burnett', father_name: 'Addison Justice', address: 'Ap #814-213 Sem Rd.' },
  { name: 'Amir', birthday: '2015-03-24', mother_name: 'Jasmine Ramos', father_name: 'Kasper Odom', address: 'Ap #128-3848 Nisl. St.' },
  { name: 'Jorden', birthday: '2015-03-05', mother_name: 'Bell Rhodes', father_name: 'Lars Fitzgerald', address: 'P.O. Box 324, 1229 Varius. Rd.' },
  { name: 'Lev', birthday: '2015-03-26', mother_name: 'Phoebe Mason', father_name: 'Herrod Jones', address: 'Ap #355-8571 Neque Av.' },
  { name: 'Vivian', birthday: '2015-10-31', mother_name: 'Jemima Maxwell', father_name: 'Luke Daugherty', address: 'P.O. Box 147, 4733 Duis Rd.' },
  { name: 'Tasha', birthday: '2014-03-18', mother_name: 'Dakota Benjamin', father_name: 'Quamar Santos', address: '4224 Ante Road' },
  { name: 'Colin', birthday: '2015-11-10', mother_name: 'Urielle West', father_name: 'Rashad Harrington', address: 'P.O. Box 740, 2807 A, Street' },
  { name: 'Adena', birthday: '2014-08-11', mother_name: 'Jordan Paul', father_name: 'Xanthus Harding', address: 'Ap #189-7493 Vestibulum Rd.' },
  { name: 'Darryl', birthday: '2014-11-14', mother_name: 'Brianna Wynn', father_name: 'Neil Short', address: 'P.O. Box 439, 8440 Pellentesque Road' },
  { name: 'Winifred', birthday: '2014-11-09', mother_name: 'Quemby Page', father_name: 'Emerson Small', address: 'Ap #122-5523 Aenean Ave' },
  { name: 'Elliott', birthday: '2015-01-16', mother_name: 'Cleo Copeland', father_name: 'Hamish Fowler', address: 'Ap #928-7351 Arcu. St.' },
  { name: 'Ciaran', birthday: '2016-05-21', mother_name: 'Leila Chen', father_name: 'Brennan Thomas', address: '807-5947 Purus. Av.' },
  { name: 'Magee', birthday: '2014-11-07', mother_name: 'Dominique Duffy', father_name: 'Howard Haynes', address: 'Ap #353-831 Ut St.' },
  { name: 'Lacy', birthday: '2016-01-31', mother_name: 'Aimee Robles', father_name: 'Myles Roth', address: 'P.O. Box 626, 9177 Tellus, Rd.' },
  { name: 'Finn', birthday: '2014-04-11', mother_name: 'Shea Hall', father_name: 'Chancellor Montgomery', address: '354-6074 Convallis Road' },
  { name: 'Jael', birthday: '2015-12-24', mother_name: 'Lucy Wright', father_name: 'Valentine Ballard', address: 'Ap #231-3805 Ut Av.' },
  { name: 'Sean', birthday: '2014-07-20', mother_name: 'Tara Garrett', father_name: 'Tanner Keller', address: 'Ap #459-4830 Porttitor Street' },
  { name: 'Xyla', birthday: '2015-05-09', mother_name: 'Zia Torres', father_name: 'Salvador Frederick', address: '5999 Odio Rd.' },
  { name: 'Noel', birthday: '2015-11-13', mother_name: 'Remedios Chang', father_name: 'John Brewer', address: '675-2112 Donec Rd.' },
  { name: 'Xerxes', birthday: '2014-08-04', mother_name: 'Myra Elliott', father_name: 'Howard Cruz', address: 'Ap #714-7078 Lorem Av.' },
  { name: 'Halla', birthday: '2015-01-23', mother_name: 'Gloria Christian', father_name: 'Caldwell Hayes', address: 'Ap #148-6536 Dolor. Rd.' },
  { name: 'Driscoll', birthday: '2014-10-02', mother_name: 'Libby Mcmahon', father_name: 'Chadwick Jimenez', address: 'Ap #400-9988 A Road' },
  { name: 'Ina', birthday: '2015-09-17', mother_name: 'Charity Clark', father_name: 'Grant Dickerson', address: 'P.O. Box 228, 1322 Diam. St.' },
  { name: 'Ian', birthday: '2015-03-13', mother_name: 'Jeanette Roberts', father_name: 'Victor Cunningham', address: 'Ap #574-5831 Phasellus Street' },
  { name: 'Jolie', birthday: '2015-06-24', mother_name: 'Gisela Sykes', father_name: 'Oliver Combs', address: 'P.O. Box 396, 8260 Adipiscing Avenue' },
  { name: 'Tatum', birthday: '2015-11-12', mother_name: 'Lacy Simmons', father_name: 'Lucian Aguilar', address: '998-7953 Neque. Av.' },
  { name: 'Jacqueline', birthday: '2014-11-07', mother_name: 'Sophia Hansen', father_name: 'Lucius Huber', address: 'Ap #279-6744 Nec, Av.' },
  { name: 'Dean', birthday: '2015-03-25', mother_name: 'Haviva Greene', father_name: 'Dylan Madden', address: '793-4590 Lorem Street' },
  { name: 'Riley', birthday: '2014-05-11', mother_name: 'Shaeleigh Valentine', father_name: 'Nigel Zamora', address: '3423 Morbi Ave' },
  { name: 'Malcolm', birthday: '2015-08-27', mother_name: 'Basia House', father_name: 'Ezekiel Pollard', address: 'P.O. Box 829, 8889 Amet St.' },
  { name: 'Wyatt', birthday: '2014-09-13', mother_name: 'Rylee Pacheco', father_name: 'Matthew Griffin', address: '1916 Pede. St.' },
  { name: 'Phelan', birthday: '2015-02-24', mother_name: 'Pascale Roy', father_name: 'Hyatt Adkins', address: '514-1378 Elit. Road' },
  { name: 'Gregory', birthday: '2014-10-21', mother_name: 'Halla Rice', father_name: 'Troy Goff', address: '4508 Bibendum. Rd.' },
  { name: 'Samantha', birthday: '2014-08-17', mother_name: 'Keely Tillman', father_name: 'Hashim Foster', address: 'P.O. Box 964, 5482 Erat Av.' },
  { name: 'Wyatt', birthday: '2016-04-15', mother_name: 'Stephanie Beasley', father_name: 'Edward Peters', address: 'Ap #135-6602 Nonummy Avenue' },
  { name: 'Elliott', birthday: '2016-01-10', mother_name: 'Kitra Delaney', father_name: 'Hayden Hull', address: 'P.O. Box 585, 6215 Ipsum Avenue' },
  { name: 'Evangeline', birthday: '2015-11-22', mother_name: 'Karyn Shaw', father_name: 'Victor Farrell', address: 'P.O. Box 903, 4790 Libero Av.' },
  { name: 'Daryl', birthday: '2014-04-06', mother_name: 'Regina Thornton', father_name: 'Ryder Farrell', address: 'P.O. Box 607, 9581 Nam St.' },
  { name: 'Troy', birthday: '2015-02-16', mother_name: 'Cheryl Melton', father_name: 'Cooper Kidd', address: '499-6223 Faucibus Av.' },
  { name: 'Colin', birthday: '2014-08-31', mother_name: 'Cheryl Moss', father_name: 'Clarke Hunt', address: '5308 Eu St.' },
  { name: 'Aubrey', birthday: '2014-08-25', mother_name: 'Medge Suarez', father_name: 'Kadeem Little', address: '1936 Justo. Ave' },
  { name: 'Helen', birthday: '2015-11-04', mother_name: 'Meredith Lindsay', father_name: 'Malcolm Gould', address: 'Ap #987-709 Integer Rd.' },
  { name: 'Wayne', birthday: '2014-01-10', mother_name: 'Brooke Gordon', father_name: 'David Fleming', address: 'Ap #555-1644 Proin Rd.' },
  { name: 'Sybil', birthday: '2015-05-27', mother_name: 'Hiroko Leach', father_name: 'Joseph Pennington', address: '5770 Elementum St.' },
  { name: 'Vincent', birthday: '2014-03-25', mother_name: 'Amaya Harrington', father_name: 'William Langley', address: 'P.O. Box 428, 8674 Et St.' },
  { name: 'Roth', birthday: '2016-03-17', mother_name: 'Winter Aguilar', father_name: 'Ross Dalton', address: 'P.O. Box 174, 651 Mauris Street' },
  { name: 'Arthur', birthday: '2014-08-30', mother_name: 'Quintessa Hendrix', father_name: 'Carter Wolfe', address: 'Ap #701-1150 Egestas. Rd.' },
  { name: 'Leah', birthday: '2015-10-23', mother_name: 'Kellie Vasquez', father_name: 'Dexter Lindsey', address: 'Ap #144-7926 Sed St.' },
  { name: 'Tad', birthday: '2015-09-22', mother_name: 'Xyla Freeman', father_name: 'Jerome Erickson', address: 'P.O. Box 778, 5528 Urna St.' },
  { name: 'MacKensie', birthday: '2015-02-05', mother_name: 'Miranda Cross', father_name: 'Victor Singleton', address: '551-372 In Road' },
  { name: 'Yuri', birthday: '2015-09-26', mother_name: 'Morgan Russell', father_name: 'Orson Wolf', address: 'P.O. Box 293, 3422 Bibendum. Avenue' },
  { name: 'Elijah', birthday: '2014-06-06', mother_name: 'Alexandra Hester', father_name: 'Vaughan Robles', address: '553-3004 Mattis Road' },
  { name: 'Britanney', birthday: '2014-06-13', mother_name: 'Quincy Barry', father_name: 'Dennis Carson', address: 'P.O. Box 987, 5745 Orci St.' },
  { name: 'Iola', birthday: '2014-11-21', mother_name: 'Kevyn Aguilar', father_name: 'Drew Mcpherson', address: 'P.O. Box 925, 1607 Massa. St.' },
  { name: 'Jared', birthday: '2014-02-01', mother_name: 'Ifeoma Pratt', father_name: 'Lars Howard', address: '5440 Ac Rd.' },
  { name: 'Nola', birthday: '2016-04-28', mother_name: 'Gisela Rocha', father_name: 'Hayes Morris', address: '2998 Neque Street' },
  { name: 'Hollee', birthday: '2015-02-13', mother_name: 'Ria Barlow', father_name: 'August Langley', address: '432-2958 Nulla St.' },
  { name: 'Hop', birthday: '2016-02-21', mother_name: 'Serena Britt', father_name: 'Elton Middleton', address: 'Ap #998-8543 Phasellus Street' },
  { name: 'Jordan', birthday: '2014-09-18', mother_name: 'Claire Vazquez', father_name: 'Conan Harper', address: 'Ap #528-9994 Ac Av.' },
  { name: 'Linus', birthday: '2016-06-11', mother_name: 'Quintessa Vang', father_name: 'Bevis Whitney', address: 'Ap #290-6945 Convallis Road' },
  { name: 'Odessa', birthday: '2014-02-02', mother_name: 'Marcia Branch', father_name: 'Tarik Holmes', address: '3867 Dolor Avenue' },
  { name: 'Dexter', birthday: '2014-05-30', mother_name: 'Karyn Williamson', father_name: 'Jerome Estes', address: '140-1213 Convallis Ave' },
  { name: 'Hector', birthday: '2014-01-16', mother_name: 'Hollee Griffith', father_name: 'Alvin Holden', address: 'Ap #926-6711 Semper Street' },
  { name: 'Stuart', birthday: '2014-09-12', mother_name: 'Leila David', father_name: 'Richard Fuentes', address: '8765 Neque Road' },
  { name: 'Flynn', birthday: '2015-03-02', mother_name: 'Brenda Salazar', father_name: 'Lance Miles', address: '5250 Amet, Road' },
  { name: 'Adena', birthday: '2014-09-30', mother_name: 'Christen Hicks', father_name: 'Tarik Lara', address: 'P.O. Box 886, 2547 Ac, Rd.' },
  { name: 'Hiroko', birthday: '2014-04-24', mother_name: 'Alfreda Sherman', father_name: 'Marsden Caldwell', address: '8700 Magna. Rd.' },
  { name: 'Morgan', birthday: '2014-05-26', mother_name: 'Ursa Espinoza', father_name: 'Jameson Kramer', address: '125-5542 Placerat, Av.' },
  { name: 'Samuel', birthday: '2014-09-27', mother_name: 'Chastity Meyer', father_name: 'Fletcher Frank', address: '1136 Tristique Ave' },
  { name: 'Daniel', birthday: '2016-01-10', mother_name: 'Priscilla Sosa', father_name: 'Lane Rollins', address: '1083 Urna St.' },
  { name: 'Kelsey', birthday: '2014-06-27', mother_name: 'Unity Reese', father_name: 'Francis Savage', address: '9578 Fermentum Street' },
  { name: 'Zeus', birthday: '2015-12-04', mother_name: 'Melanie Guthrie', father_name: 'Randall Stephenson', address: 'Ap #327-2817 Sed Rd.' },
  { name: 'Stella', birthday: '2015-09-29', mother_name: 'Cheyenne Yang', father_name: 'Hashim Evans', address: 'Ap #614-9047 Integer Rd.' },
  { name: 'Zephania', birthday: '2014-03-06', mother_name: 'Cally Salinas', father_name: 'Lawrence Velez', address: 'P.O. Box 157, 8556 Libero. Street' },
  { name: 'Ethan', birthday: '2016-04-26', mother_name: 'Unity Christian', father_name: 'Graiden Ayala', address: 'P.O. Box 351, 5555 Vivamus Road' },
  { name: 'Burton', birthday: '2015-05-22', mother_name: 'Leslie Roberson', father_name: 'Lucas Morin', address: 'P.O. Box 647, 3210 Mauris St.' },
  { name: 'Irma', birthday: '2015-06-20', mother_name: 'Bryar Marks', father_name: 'Vaughan Tyler', address: '2974 Sem, Ave' },
  { name: 'Odette', birthday: '2015-03-11', mother_name: 'Isadora Mclaughlin', father_name: 'Preston Greer', address: 'Ap #383-1346 Nulla Road' }
]

babies.each do |baby|
  Baby.find_or_create_by(baby)
end
