version: 2.0

jobs:
  build:
    working_directory: ~/kinedu_lab
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: kinedu_lab_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - kinedu-lab-{{ checksum "Gemfile.lock" }}
            - kinedu-lab-
      - run:
          name: Install bundler
          command: gem install bundler -v 2.1.3

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: kinedu-lab-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: kinedu-lab-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Rspec tests
          command: bundle exec rspec spec/
